name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run coverage
      - uses: actions/upload-artifact@v4
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: test-results
          path: junit.xml
