name: Release
on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Update package.json version
        uses: erlete/version-updater@v2.0
        with:
          target-file: package.json